server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: deuda-service
          uri: lb://deuda-service
          predicates:
            - Path=/api/deudas/**
          filters:
            - AuthFilter
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/auth/**
  