server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: deuda-service
          uri: lb://deuda-service
          predicates:
            - Path=/api/deudas/**
          filters:
            - AuthFilter
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/auth/**
  datasource:
      url: jdbc:postgresql://localhost:5432/economiadb
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: root 
    jpa:
      database: POSTGRESQL
      show-sql : false
      hibernate:
        ddl-auto: update

app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 86400000   